2020-12-24 01:35:15.2884 ERROR Ha ocurrido un error en LoginController. Mensaje: No se pudo conectar a la base de datos. | Usuario: 
2020-12-24 01:35:34.8916 ERROR Ha ocurrido un error en LoginController. Mensaje: No se pudo conectar a la base de datos. | Usuario: 
2020-12-24 02:24:56.7228 ERROR Ha ocurrido un error en LoginController. Mensaje: No se pudo conectar a la base de datos. | Usuario: 
2020-12-24 02:24:59.4768 ERROR Ha ocurrido un error en LoginController. Mensaje: No se pudo conectar a la base de datos. | Usuario: 
2020-12-24 02:39:24.0964 ERROR Ha ocurrido un error en LoginController. Mensaje: No se pudo conectar a la base de datos. | Usuario:  | Exception: ProdeinWebApi.Application.Common.Exceptions.BaseDeDatosException: Se produjo una excepción de tipo 'ProdeinWebApi.Application.Common.Exceptions.BaseDeDatosException'.
   en ProdeinWebApi.Application.Data.DAO.DAO.Conectar() en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Data\DAO\DAO.cs:línea 69
   en ProdeinWebApi.Application.Data.DAO.DAOUsuario.ConsultarUsuarioLogin(Entidad entidad) en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Data\DAO\DAOUsuario.cs:línea 43
   en ProdeinWebApi.Application.Business_Logic.Command.Usuario.ComandoConsultarUsuarioLogin.Ejecutar() en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Business_Logic\Command\Usuario\ComandoConsultarUsuarioLogin.cs:línea 23
   en ProdeinWebApi.Application.Controllers.LoginController.Authenticate(Usuario login) en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Controllers\LoginController.cs:línea 53
2020-12-24 02:42:03.4443 ERROR Ha ocurrido un error en LoginController. Mensaje: No se pudo conectar a la base de datos. | Usuario:  | Message Exception: Se produjo una excepción de tipo 'ProdeinWebApi.Application.Common.Exceptions.BaseDeDatosException'.
2020-12-24 02:47:29.7980 ERROR Ha ocurrido un error en LoginController. Mensaje: No se pudo conectar a la base de datos. | Usuario:  | Exception: MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'localhost' for user 'prodeinAdminDB' using method 'mysql_native_password' failed with message: Access denied for user 'prodeinAdminDB'@'localhost' (using password: YES) ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'prodeinAdminDB'@'localhost' (using password: YES)
   en MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ContinueAuthentication(Byte[] data)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.HandleAuthChange(MySqlPacket packet)
   en MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   en MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   en MySql.Data.MySqlClient.NativeDriver.Open()
   en MySql.Data.MySqlClient.Driver.Open()
   en MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   en MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   en MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   en MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   en MySql.Data.MySqlClient.MySqlPool.GetConnection()
   en MySql.Data.MySqlClient.MySqlConnection.Open()
   en ProdeinWebApi.Application.Data.DAO.DAO.Conectar() en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Data\DAO\DAO.cs:línea 64
2020-12-24 02:49:04.5424 ERROR Ha ocurrido un error en LoginController. Mensaje: No se pudo conectar a la base de datos. | Usuario:  | Exception: Authentication to host 'localhost' for user 'prodeinAdminDB' using method 'mysql_native_password' failed with message: Access denied for user 'prodeinAdminDB'@'localhost' (using password: YES)
2020-12-24 02:51:56.2039 ERROR Exepcion general. Mensaje excepcion: El valor no puede ser nulo.
Nombre del parámetro: Error al ejecutar el StoredProcedure MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect number of arguments for PROCEDURE prodeindb.ConsultarUsuarioLogin; expected 1, got 0
   en MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   en MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   en MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   en MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   en MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   en MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   en MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   en ProdeinWebApi.Application.Data.DAO.DAO.EjecutarReader() en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Data\DAO\DAO.cs:línea 96 | Trace:    en ProdeinWebApi.Application.Data.DAO.DAO.EjecutarReader() en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Data\DAO\DAO.cs:línea 102
   en ProdeinWebApi.Application.Data.DAO.DAOUsuario.ConsultarUsuarioLogin(Entidad entidad) en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Data\DAO\DAOUsuario.cs:línea 46
   en ProdeinWebApi.Application.Business_Logic.Command.Usuario.ComandoConsultarUsuarioLogin.Ejecutar() en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Business_Logic\Command\Usuario\ComandoConsultarUsuarioLogin.cs:línea 23
   en ProdeinWebApi.Application.Controllers.LoginController.Authenticate(Usuario login) en C:\Users\jesus\Documents\prodein\AppWeb\Prodein\ProdeinRepo\Back-End\ProdeinWebApi\Application\Controllers\LoginController.cs:línea 53
